[project]
name = "5-lang-serve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "langchain-community>=0.3.27",
    "langserve>=0.3.1",
    "uvicorn>=0.35.0",
    "sse_starlette>=1.8.2",
]
